### ISSUE TITLE
Is the .jld extension now mandatory?

### ISSUE THREAD

**Issue by mweastwood** [JuliaLang/JLD.jl#36]
I think this is the result of #30, but I now get errors like:
```
ERROR: LoadError: LoadError: FileIO.File{FileIO.DataFormat{:UNKNOWN}}("/tmp/juliao8DRo1") couldn't be recognized by FileIO.
```
when I try to read/write to a filename without the .jld extension.

Is this the new status quo?

**Comment by timholy** [comment]
I can't reproduce:
```jl
julia> using JLD

julia> jldopen("/tmp/junk", "w") do file
           write(file, "a", rand(2))
       end

julia> 
tim@diva:~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.1-pre+22 (2015-11-01 00:06 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 669222e* (4 days old release-0.4)
|__/                   |  x86_64-linux-gnu

julia> using FileIO

julia> load("/tmp/junk")
Dict{ByteString,Any} with 1 entry:
  "a" => [0.2054425503298385,0.42643025987841376]
```
Maybe that file doesn't exist? I noticed that the FileIO error message is misleading when that's the case. (If so, pls file issue, or PR :smile:, with FileIO.)

**Comment by mweastwood** [comment]
My apologies for the lazy issue reporting. I should have been more explicit about what I'm doing to get the error.

This is how to reproduce the error I'm seeing:
```
using JLD
save(tempname(),"foo",1)
```

Adding .jld to the end of the filename makes the error go away. I'm on my phone right now, but I'll edit with version numbers when I get to my computer.

**Comment by timholy** [comment]
Oh, you're getting the error only when you **write** a new file? Yes, now that `save` is generic, it has to be able to guess the format either from the filename or from magic bytes; if it's a new file, there are no magic bytes, so either you need to supply clues in the extension or use
```jl
julia> save(File(format"JLD", fn), "foo", 1)
```
Not needed for `load`, since it can rely on the magic bytes:
```jl
julia> vars = load(fn)
Dict{ByteString,Any} with 1 entry:
  "foo" => 1
```

**Comment by mweastwood** [comment]
That makes sense. I guess that's an unavoidable drawback of a generic save. This issue was filed mostly because I was surprised to see code stop working and there was no documentation on this change (so I wasn't sure if it was intentional).

I'll open a PR to document this.

**Comment by timholy** [comment]
Thanks. This is definitely in the category of "unanticipated consequence." Obvious really, except the way I came at it was "too many packages want to define save"->"create FileIO"->"rebase JLD on FileIO".

It occurs to me that with a little tweaking we could probably make `JLD.save` work. There was some revamping how the whole package dispatch thing works in FileIO, and I think the current standard is that packages _shouldn't_ `import FileIO.save`---I think `FileIO.save` will call `JLD.save` directly. Assuming that's right (it's been a while since I checked), then `JLD.save` should work, which might be nicer than the `format` string solution above.
